import rclpy
from rclpy.node import Node
from geometry_msgs.msg import Twist
import socket

# !!! CONFIGURATION !!!
# Replace this with the AGV Robot's IP Address (e.g., '192.168.1.105')
UDP_IP = '10.165.81.238'
UDP_PORT = 15000

class CmdVelToUDP(Node):
    def __init__(self):
        super().__init__('cmd_vel_to_udp')
        self.sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        
        # Subscribe to the topic generated by your keyboard/joystick node
        self.sub = self.create_subscription(
            Twist,
            '/cmd_vel_teleop', 
            self.cb,
            10
        )
        self.get_logger().info(f'Forwarding /cmd_vel_teleop -> UDP {UDP_IP}:{UDP_PORT}')

    def cb(self, msg):
        # Format: "linear_x linear_y angular_z"
        # Using f-string with limited precision to save bandwidth
        data = f"{msg.linear.x:.3f} {msg.linear.y:.3f} {msg.angular.z:.3f}"
        self.sock.sendto(data.encode(), (UDP_IP, UDP_PORT))

def main():
    rclpy.init()
    rclpy.spin(CmdVelToUDP())
    rclpy.shutdown()

if __name__ == '__main__':
    main()
